### ISSUE TITLE
For stocks, nothing shows up if I set the interval to anything below 1d.

### ISSUE THREAD

**Issue by fangfufu** [loiccoyle/tinyticker#41]
Thank you for this excellent project. When I am getting this project to display stocks, if I set the interval to anything below 1 day, nothing shows up on my ePaper display. Is there a fix for this? The setting in question is show below in the red box: 
![image](https://github.com/loiccoyle/tinyticker/assets/2323403/2be96778-e03c-424c-bca8-ec13eba0300b)

**Comment by fangfufu** [comment]
Ah this turns out to work when the stock market is open. It would be nice if it also works when the stock market is closed.

**Comment by loiccoyle** [comment]
> Ah this turns out to work when the stock market is open. It would be nice if it also works when the stock market is closed.

Yeah that is the current behaviour I did it like this because if I'm displaying both stocks and crypto assets, I don't really care about the stock display on the weekends for example, but I can see why it is confusing. 

I had plans to make the this toggleable  (#37), but I haven't gotten around to it. I'll see if I can do it this week.

**Comment by loiccoyle** [comment]
with #42  I added the toggle, I'll close this issue, feel free to reopen if you run into a problem.
